version: "3.8"

services:
  auth0:
    image: wiremock/wiremock:2.30.0
    volumes:
      - ./dockerfiles/wiremock/__files:/home/wiremock/__files
      - ./dockerfiles/wiremock/mappings:/home/wiremock/mappings
    command: --port 8080 --verbose
    healthcheck:
      test: "curl -f http://localhost:8080/__admin || false"
      interval: 1s
      retries: 60
    expose:
      - "8080"
    ports:
      - "8080:8080"
